name: Build Syncthing macOS Debug DMG (On-Demand)

on:
  workflow_dispatch:

jobs:
  build-debug-dmg:
    name: Build Debug DMG
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build debug target
        run: |
          make debug-dmg

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: syncthing-macos-dmg-debug-dmg
          path: Build/Products/Debug/*.dmg
